name: publish
on:
  push:
    tags:
      - "v*.*.*"
env:
  CARGO_TERM_COLOR: always
jobs:
  release-build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - run: pacman -Sy
      - run: pacman -S  --noconfirm base-devel nodejs rustup python python-pytorch python-torchvision python-gobject opencv clang dpkg git
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: rustup toolchain install nightly
      - run: rustup default nightly
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - name: Build packages
        run: |
          cargo install cargo-binstall
          cargo binstall -y --force cargo-aur
          cargo binstall -y --force cargo-deb
          cargo binstall -y --force cargo-generate-rpm

          cargo build --release

          cargo aur
          cargo deb
          cargo generate-rpm
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }} (draft)
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: false
          generate_release_notes: true
          preserve_order: false
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: eymate.tar.gz
          path: target/cargo-aur/*.tar.gz
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "target/cargo-aur/*.tar.gz"
          release_id: ${{ steps.create_release.outputs.id }}
          update_release_body: ${{ github.ref }}
          update_release_body_append: "true"
          overwrite: true
          verbose: true
      - name: Makepkg
        run: |
          useradd builduser -m
          passwd -d builduser
          chmod 777 -R .
          su builduser -c "makepkg -D target/cargo-aur/"
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: eymate.pkg.tar.zst
          path: target/cargo-aur/*.pkg.tar.zst
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "target/cargo-aur/*.pkg.tar.zst"
          release_id: ${{ steps.create_release.outputs.id }}
          update_release_body: ${{ github.ref }}
          update_release_body_append: "true"
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: eymate.deb
          path: target/debian/*.deb
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "target/debian/*.deb"
          release_id: ${{ steps.create_release.outputs.id }}
          update_release_body: ${{ github.ref }}
          update_release_body_append: "true"
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: eymate.rpm
          path: target/generate-rpm/*.rpm
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "target/generate-rpm/*.rpm"
          release_id: ${{ steps.create_release.outputs.id }}
          update_release_body: ${{ github.ref }}
          update_release_body_append: "true"
